// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package provider

import mock "github.com/stretchr/testify/mock"

// MockCryptographer is an autogenerated mock type for the Cryptographer type
type MockCryptographer struct {
	mock.Mock
}

// Decode provides a mock function with given fields: encodedValue
func (_m *MockCryptographer) Decode(encodedValue []byte) ([]byte, error) {
	ret := _m.Called(encodedValue)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(encodedValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(encodedValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encode provides a mock function with given fields: value
func (_m *MockCryptographer) Encode(value []byte) ([]byte, error) {
	ret := _m.Called(value)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
