// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package provider

import mock "github.com/stretchr/testify/mock"

// MockDataSaver is an autogenerated mock type for the DataSaver type
type MockDataSaver struct {
	mock.Mock
}

// ReadData provides a mock function with given fields: key
func (_m *MockDataSaver) ReadData(key []byte) ([]byte, error) {
	ret := _m.Called(key)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveData provides a mock function with given fields: key, encodedValue
func (_m *MockDataSaver) SaveData(key []byte, encodedValue []byte) error {
	ret := _m.Called(key, encodedValue)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(key, encodedValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
