name: build

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.0-buster
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: set up go 1.16
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      id: go
        
    - name: checkout
      uses: actions/checkout@v2

    - name: build and test
      run: |
        go test -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
        cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mocks" | grep -v "_mock" > $GITHUB_WORKSPACE/profile.cov
      env:
        GOFLAGS: "-mod=vendor"
      
    - name: install golangci-lint and goveralls
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.39.0
        GO111MODULE=off go get -u github.com/mattn/goveralls
    
    - name: run linters
      run: $GITHUB_WORKSPACE/golangci-lint run ./... --config .golangci.yml
      env:
        GOFLAGS: "-mod=vendor"

    - name: submit coverage
      run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
